// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Prefer the unpooled/direct connection for migrations when available
    // (e.g. Neon's DATABASE_URL_UNPOOLED) — Prisma Migrate's session-level
    // locking is unreliable through a transaction-mode connection pooler.
    // The running app itself connects independently via DATABASE_URL
    // (see src/lib/db.ts), so this only affects CLI/migration commands.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
